version: '2.2'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URL: "mongodb+srv://AkshayMakwana:Akshay123@cluster0.zmta9.mongodb.net/AADI-DB"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
